name: Willchain Explorer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build Frontend 
      run: bash ./run.sh


